name: Publish to Zenodo

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  publish-fig:
    runs-on: ubuntu-latest
    name: Publish code to Zenodo
    permissions:
      contents: write
    steps:
      - name: Checkout the contents of your repository
        uses: actions/checkout@v4

      - name: Create ZIP of code folder
        run: zip -r code.zip code/

      - name: Debug `.zenodo.json` existence
        run: |
          if [ ! -f ".zenodo.json" ]; then
            echo "Error: .zenodo.json does not exist!"
            exit 1
          else
            echo "Contents of .zenodo.json:"
            cat .zenodo.json
          fi

      - name: Get or create Zenodo deposition
        id: zenodo_deposition
        env:
          ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
        run: |
          ID_STORAGE_FILE=".zenodo_ids.json"
          
          echo "Testing Zenodo API access..."
          TEST_RESPONSE=$(curl -s -X GET "https://sandbox.zenodo.org/api/deposit/depositions" \
            -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN")

          MESSAGE=$(echo "$TEST_RESPONSE" | jq -r '.message // .[0].message')
          if [[ "$MESSAGE" != "null" ]]; then
            echo "ERROR: API access issue - $MESSAGE"
            exit 1
          fi
          
          echo "Creating new deposition..."
          CREATE_RESPONSE=$(curl -s -X POST "https://sandbox.zenodo.org/api/deposit/depositions" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN" \
            -d '{"metadata": {"title": "My Dataset", "upload_type": "dataset", "description": "Description", "creators": [{"name": "Author Name", "affiliation": "Affiliation"}]}}')

          DEPOSITION_ID=$(echo "$CREATE_RESPONSE" | jq -r '.id')
          CONCEPT_ID=$(echo "$CREATE_RESPONSE" | jq -r '.conceptrecid')

          if [[ -z "$DEPOSITION_ID" || "$DEPOSITION_ID" == "null" ]]; then
            echo "ERROR: Failed to create deposition"
            echo "Response: $CREATE_RESPONSE"
            exit 1
          fi
          
          echo "Created deposition: ID = $DEPOSITION_ID, Concept ID = $CONCEPT_ID"
          echo "{\"concept_id\":\"$CONCEPT_ID\",\"deposition_id\":\"$DEPOSITION_ID\"}" > "$ID_STORAGE_FILE"

          echo "DEPOSITION_ID=$DEPOSITION_ID" >> $GITHUB_ENV
          echo "CONCEPT_ID=$CONCEPT_ID" >> $GITHUB_ENV
          echo "deposition_id=$DEPOSITION_ID" >> $GITHUB_OUTPUT
          echo "concept_id=$CONCEPT_ID" >> $GITHUB_OUTPUT

      - name: Upload the ZIP file to Zenodo
        env:
          ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
          DEPOSITION_ID: ${{ env.DEPOSITION_ID }}
        run: |
          echo "Uploading ZIP file to Zenodo..."
          
          BUCKET_URL=$(curl -s -X GET "https://sandbox.zenodo.org/api/deposit/depositions/$DEPOSITION_ID" \
            -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN" | jq -r '.links.bucket')

          if [[ "$BUCKET_URL" == "null" ]]; then
            echo "ERROR: Failed to get bucket URL"
            exit 1
          fi

          curl --progress-bar -s -X POST \
            "$BUCKET_URL" \
            -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN" \
            -H "Content-Type: application/octet-stream" \
            --upload-file code.zip

          echo "File uploaded successfully."

      - name: Publish deposition
        env:
          ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
          DEPOSITION_ID: ${{ env.DEPOSITION_ID }}
        run: |
          echo "Publishing deposition ID: $DEPOSITION_ID"

          PUBLISH_RESPONSE=$(curl -s -X POST \
            "https://sandbox.zenodo.org/api/deposit/depositions/$DEPOSITION_ID/actions/publish" \
            -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN")

          echo "Publish Response: $PUBLISH_RESPONSE"

      - name: Debug Zenodo Concept
        env:
          ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
          CONCEPT_ID: ${{ env.CONCEPT_ID }}
        run: |
          echo "Checking concept ID: $CONCEPT_ID"
          RESPONSE=$(curl -s -X GET "https://sandbox.zenodo.org/api/records/$CONCEPT_ID" \
            -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN")
          echo "Response: $RESPONSE"

      
      # - name: Upload the ZIP file to Zenodo
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
      #   uses: zenodraft/action@0.13.3
      #   with:
      #     concept: ${{ steps.zenodo_deposition.outputs.concept_id }}
      #     metadata: .zenodo.json
      #     publish: true
      #     sandbox: true
      #     filenames: |
      #       code.zip
      #     verbose: true
