name: Publish to Zenodo

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-fig:
    runs-on: ubuntu-latest
    name: Publish code to Zenodo
    permissions:
      contents: write
    steps:
      - name: Checkout the contents of your repository
        uses: actions/checkout@v4

      - name: Create ZIP of code folder
        run: zip -r code.zip code/

      - name: Debug `.zenodo.json` existence
        run: |
          if [ ! -f ".zenodo.json" ]; then
            echo "Error: .zenodo.json does not exist!"
            exit 1
          else
            echo "Contents of .zenodo.json:"
            cat .zenodo.json
          fi

      - name: Get or create Zenodo deposition
        id: zenodo_deposition
        env:
          ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
        run: |
          echo "Creating new deposition..."
          CREATE_RESPONSE=$(curl -s -X POST "https://sandbox.zenodo.org/api/deposit/depositions" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN" \
            -d @.zenodo.json)

          DEPOSITION_ID=$(echo "$CREATE_RESPONSE" | jq -r '.id')
          CONCEPT_ID=$(echo "$CREATE_RESPONSE" | jq -r '.conceptrecid')

          if [[ -z "$DEPOSITION_ID" || "$DEPOSITION_ID" == "null" ]]; then
            echo "ERROR: Failed to create deposition"
            echo "Response: $CREATE_RESPONSE"
            exit 1
          fi
          
          echo "Created deposition: ID = $DEPOSITION_ID, Concept ID = $CONCEPT_ID"
          echo "DEPOSITION_ID=$DEPOSITION_ID" >> $GITHUB_ENV
          echo "CONCEPT_ID=$CONCEPT_ID" >> $GITHUB_ENV

      - name: Upload the ZIP file to Zenodo
        env:
          ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
          DEPOSITION_ID: ${{ env.DEPOSITION_ID }}
        run: |
          echo "Fetching Zenodo bucket URL..."
          BUCKET_URL=$(curl -s -X GET "https://sandbox.zenodo.org/api/deposit/depositions/$DEPOSITION_ID" \
            -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN" | jq -r '.links.bucket')

          if [[ "$BUCKET_URL" == "null" ]]; then
            echo "ERROR: Failed to get bucket URL"
            exit 1
          fi

          echo "Uploading ZIP file to Zenodo..."
          curl --progress-bar -X PUT \
            "$BUCKET_URL/code.zip" \
            -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN" \
            -H "Content-Type: application/zip" \
            --upload-file code.zip

          echo "File uploaded successfully."

      - name: Publish deposition
        env:
          ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
          DEPOSITION_ID: ${{ env.DEPOSITION_ID }}
        run: |
          echo "Publishing deposition ID: $DEPOSITION_ID"

          PUBLISH_RESPONSE=$(curl -s -X POST \
            "https://sandbox.zenodo.org/api/deposit/depositions/$DEPOSITION_ID/actions/publish" \
            -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN")

          echo "Publish Response: $PUBLISH_RESPONSE"
