name: Publish to Zenodo

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-fig:
    runs-on: ubuntu-latest
    name: Publish code to Zenodo
    steps:
      - name: Checkout the contents of your repository
        uses: actions/checkout@v4

      - name: Create ZIP of code folder
        run: zip -r code.zip code/

      - name: Get existing Concept ID or create new deposition
        id: zenodo_deposition
        env:
          ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
        run: |
          # Ensure the access token is set
          if [ -z "$ZENODO_ACCESS_TOKEN" ]; then
            echo "Error: ZENODO_ACCESS_TOKEN is not set."
            exit 1
          fi

          # Fetch existing depositions from Zenodo API
          RESPONSE=$(curl -s -X GET "https://sandbox.zenodo.org/api/deposit/depositions" \
            -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN")

          # Validate JSON response
          if ! echo "$RESPONSE" | jq . >/dev/null 2>&1; then
            echo "Error: Invalid JSON response from Zenodo API."
            exit 1
          fi

          # Extract the latest Deposition ID and Concept ID
          DEPOSITION_ID=$(echo "$RESPONSE" | jq -r '.[0].id // empty')
          CONCEPT_ID=$(echo "$RESPONSE" | jq -r '.[0].conceptrecid // empty')

          if [ -z "$CONCEPT_ID" ]; then
            echo "Error: No existing Concept ID found. Creating a new one."
            NEW_RESPONSE=$(curl -s -X POST "https://sandbox.zenodo.org/api/deposit/depositions" \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN" \
              -d @.zenodo.json)
            DEPOSITION_ID=$(echo "$NEW_RESPONSE" | jq -r '.id // empty')
            CONCEPT_ID=$(echo "$NEW_RESPONSE" | jq -r '.conceptrecid // empty')
            if [ -z "$DEPOSITION_ID" ] || [ -z "$CONCEPT_ID" ]; then
              echo "Error: Failed to create new Concept ID."
              exit 1
            fi
          else
            echo "Using existing Concept ID: $CONCEPT_ID"
            
            # Create a new version from existing deposition
            VERSION_RESPONSE=$(curl -s -X POST "https://sandbox.zenodo.org/api/deposit/depositions/$DEPOSITION_ID/actions/newversion" \
              -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN")

            NEW_DEPOSITION_ID=$(echo "$VERSION_RESPONSE" | jq -r '.links.latest_draft // empty' | awk -F'/' '{print $NF}')
            if [ -z "$NEW_DEPOSITION_ID" ]; then
              echo "Error: Failed to create new version."
              exit 1
            fi
            DEPOSITION_ID=$NEW_DEPOSITION_ID
          fi

          echo "Created/Using Deposition ID: $DEPOSITION_ID"
          echo "DEPOSITION_ID=$DEPOSITION_ID" >> $GITHUB_ENV

      - name: Upload the ZIP file to Zenodo
        env:
          ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
        run: |
          if [ ! -f "code.zip" ]; then
            echo "Error: code.zip file does not exist!"
            exit 1
          fi
          curl -s -X POST "https://sandbox.zenodo.org/api/deposit/depositions/$DEPOSITION_ID/files" \
            -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN" \
            -F "file=@code.zip;filename=code.zip"

      - name: Publish the Zenodo deposition
        if: success()
        env:
          ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
        run: |
          RESPONSE=$(curl -s -X POST "https://sandbox.zenodo.org/api/deposit/depositions/$DEPOSITION_ID/actions/publish" \
            -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN")
          if [[ $? -ne 0 ]]; then
            echo "Error publishing the deposition."
            exit 1
          fi
          echo "Deposition published successfully."
