name: Publish to Zenodo

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  publish-fig:
    runs-on: ubuntu-latest
    name: Publish code to Zenodo
    steps:
      - name: Checkout the contents of your repository
        uses: actions/checkout@v4

      - name: Create ZIP of code folder
        run: zip -r code.zip code/

      - name: Get or create Zenodo deposition
        id: zenodo_deposition
        env:
          ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
        run: |
          # Ensure access token is set
          if [ -z "$ZENODO_ACCESS_TOKEN" ]; then
            echo "Error: ZENODO_ACCESS_TOKEN is not set."
            exit 1
          fi
      
          echo "Token length: ${#ZENODO_ACCESS_TOKEN}"
      
          # Fetch existing depositions from Zenodo API
          RESPONSE=$(curl -s -X GET "https://sandbox.zenodo.org/api/deposit/depositions" \
            -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN")
      
          if [[ $? -ne 0 || -z "$RESPONSE" ]]; then
            echo "Error fetching deposition list from Zenodo."
            exit 1
          fi
      
          echo "Zenodo API Response: $RESPONSE"
      
          # Validate JSON response format
          if ! echo "$RESPONSE" | jq . >/dev/null 2>&1; then
            echo "Error: Invalid JSON response from Zenodo API."
            exit 1
          fi
      
          # Extract the first existing deposition ID and metadata if present
          EXISTING_DEPOSITION_ID=$(echo "$RESPONSE" | jq -r '.[0].id // empty')
          if [ -n "$EXISTING_DEPOSITION_ID" ]; then
            echo "Found existing deposition with ID: $EXISTING_DEPOSITION_ID"
      
            # Fetch the detailed metadata for the existing deposition
            METADATA_RESPONSE=$(curl -s -X GET "https://sandbox.zenodo.org/api/deposit/depositions/$EXISTING_DEPOSITION_ID" \
              -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN")
      
            if [[ $? -ne 0 || -z "$METADATA_RESPONSE" ]]; then
              echo "Error fetching metadata for deposition ID $EXISTING_DEPOSITION_ID."
              exit 1
            fi
      
            # Validate metadata response format
            if ! echo "$METADATA_RESPONSE" | jq . >/dev/null 2>&1; then
              echo "Error: Invalid metadata response from Zenodo API."
              exit 1
            fi
      
            # Extract metadata and remove unnecessary fields (such as ID, DOI)
            METADATA=$(echo "$METADATA_RESPONSE" | jq 'del(.id, .doi, .links, .created, .modified)')
      
            # Create a new deposition based on the existing metadata
            echo "Creating a new deposition based on existing metadata..."
            NEW_DEPOSITION_RESPONSE=$(curl -s -X POST "https://sandbox.zenodo.org/api/deposit/depositions" \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN" \
              --data "{\"metadata\": $METADATA}")
      
            if [[ $? -ne 0 || -z "$NEW_DEPOSITION_RESPONSE" ]]; then
              echo "Error creating new deposition."
              exit 1
            fi
      
            # Extract the new deposition ID
            NEW_DEPOSITION_ID=$(echo "$NEW_DEPOSITION_RESPONSE" | jq -r '.id // empty')
            if [ -z "$NEW_DEPOSITION_ID" ]; then
              echo "Error: Failed to retrieve new Deposition ID."
              exit 1
            fi
      
            echo "Created new deposition with ID: $NEW_DEPOSITION_ID"
          else
            # If no existing deposition is found, create a new empty deposition
            echo "No existing deposition found. Creating a new deposition..."
      
            RESPONSE=$(curl -s -X POST "https://sandbox.zenodo.org/api/deposit/depositions" \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN" \
              --data '{}')
      
            if [[ $? -ne 0 || -z "$RESPONSE" ]]; then
              echo "Error creating new deposition."
              exit 1
            fi
      
            NEW_DEPOSITION_ID=$(echo "$RESPONSE" | jq -r '.id // empty')
            if [ -z "$NEW_DEPOSITION_ID" ]; then
              echo "Error: Failed to retrieve new Deposition ID."
              exit 1
            fi
      
            echo "Created new deposition with ID: $NEW_DEPOSITION_ID"
          fi
      
          # Set the new DEPOSITION_ID as a GitHub environment variable for subsequent steps
          echo "DEPOSITION_ID=$NEW_DEPOSITION_ID" >> $GITHUB_ENV
      
      - name: Upload the ZIP file to Zenodo
        env:
          ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
        run: |
          if [ ! -f "code.zip" ]; then
            echo "Error: code.zip file does not exist!"
            exit 1
          fi
          curl -s -X POST "https://sandbox.zenodo.org/api/deposit/depositions/$DEPOSITION_ID/files" \
            -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN" \
            -F "file=@code.zip;filename=code.zip"
  
      - name: Keep in Draft Mode
        env:
          ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
        run: |
          RESPONSE=$(curl -s -X POST "https://sandbox.zenodo.org/api/deposit/depositions/$DEPOSITION_ID/actions/submit" \
            -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN")
          if [[ $? -ne 0 ]]; then
            echo "Error keeping deposition in draft mode."
            exit 1
          fi
          echo "Submission completed, kept in draft mode (not published)."

      # - name: Publish the Zenodo deposition
      #   if: success()
      #   env:
      #     ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
      #   run: |
      #     RESPONSE=$(curl -s -X POST "https://sandbox.zenodo.org/api/deposit/depositions/$DEPOSITION_ID/actions/publish" \
      #       -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN")
      #     if [[ $? -ne 0 ]]; then
      #       echo "Error publishing the deposition."
      #       exit 1
      #     fi
      #     echo "Deposition published successfully."
