name: Publish to Zenodo

# on:
#   # Trigger when you publish a release via GitHub's release page
#   release:
#     types:
#       - published

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the contents of your repository
        uses: actions/checkout@v4

      - name: Check if concept exists
        id: concept_check
        run: |
          if [[ -f "concept_id.txt" ]]; then
            echo "Concept ID found: $(cat concept_id.txt)"
            echo "::set-output name=concept_id::$(cat concept_id.txt)"
          else
            echo "::set-output name=concept_id::"
          fi

      - name: Create a new concept and store its ID
        if: steps.concept_check.outputs.concept_id == ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
        run: |
          concept_id=$(curl -X POST https://sandbox.zenodo.org/api/deposit/depositions \
            -H "Authorization: Bearer $ZENODO_SANDBOX_ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "metadata": {
                "title": "Your project title",
                "upload_type": "software",
                "description": "Description of your project"
              }
            }' | jq -r .conceptdoi)
          
          echo "Created new concept with ID: $concept_id"
          echo $concept_id > concept_id.txt
          
      - name: Create a draft snapshot of repository contents as a new version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
        uses: zenodraft/action@0.13.3
        with:
          concept: ${{ steps.concept_check.outputs.concept_id }}
          metadata: .zenodo.json
          publish: false
          sandbox: true
          filenames: code  # Only upload the 'code' folder