name: Publish to Zenodo

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manual trigger only

jobs:
  publish-fig:
    runs-on: ubuntu-latest
    name: Publish code to Zenodo
    steps:
      - name: Checkout the contents of your repository
        uses: actions/checkout@v4

      - name: Create ZIP of code folder
        run: zip -r code.zip code/

      - name: Debug `.zenodo.json` existence
        run: |
          if [ ! -f ".zenodo.json" ]; then
            echo "Error: .zenodo.json does not exist!"
            exit 1
          else
            echo "Contents of .zenodo.json:"
            cat .zenodo.json
          fi

      - name: Get or create Zenodo deposition
        id: zenodo_deposition
        env:
          ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
        run: |
          RESPONSE=$(curl -s -X GET "https://sandbox.zenodo.org/api/deposit/depositions" \
            -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN")
          if [[ $? -ne 0 ]]; then
            echo "Error fetching deposition list from Zenodo."
            exit 1
          fi
          echo "Zenodo API Response: $RESPONSE"
          
          CONCEPT_ID=$(echo "$RESPONSE" | jq -r '.[] | select(.metadata.prereserve_doi != null) | .conceptdoi' | head -n 1)
          echo "Concept ID: $CONCEPT_ID"
          
          if [ -z "$CONCEPT_ID" ]; then
            RESPONSE=$(curl -s -X POST "https://sandbox.zenodo.org/api/deposit/depositions" \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN" \
              -d @.zenodo.json)
            if [[ $? -ne 0 ]]; then
              echo "Error creating new deposition."
              exit 1
            fi
            echo "Creation response: $RESPONSE"
            DEPOSITION_ID=$(echo $RESPONSE | jq -r '.id')
            echo "Created new deposition with ID: $DEPOSITION_ID"
          else 
            DEPOSITION_ID=$(echo "$RESPONSE" | jq -r '.[] | select(.metadata.prereserve_doi != null) | .id' | head -n 1)
            echo "Using existing deposition with ID: $DEPOSITION_ID"
          fi
          
          if [ -z "$DEPOSITION_ID" ]; then
            echo "Error: DEPOSITION_ID is not set"
            exit 1
          fi
          
          echo "DEPOSITION_ID=$DEPOSITION_ID" >> $GITHUB_ENV

      - name: Upload the ZIP file to Zenodo
        uses: zenodraft/action@0.13.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
        with:
          metadata: .zenodo.json
          filenames: |
            code.zip
          sandbox: true
          publish: false
          verbose: true

      - name: Publish the Zenodo deposition
        if: success()
        env:
          ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
        run: |
          if [ -z "$DEPOSITION_ID" ]; then
            echo "Error: DEPOSITION_ID is not set"
            exit 1
          fi
          
          RESPONSE=$(curl -s -X POST "https://sandbox.zenodo.org/api/deposit/depositions/$DEPOSITION_ID/actions/publish" \
            -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN")
          if [[ $? -ne 0 ]]; then
            echo "Error publishing the deposition. Response: $RESPONSE"
            exit 1
          fi
          echo "Deposition published successfully."
