name: Publish to Zenodo

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-fig:
    runs-on: ubuntu-latest
    name: Publish code to Zenodo
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create ZIP of Code Folder
        run: zip -r code.zip code/

      - name: Get or Create Concept and Deposition on Zenodo
        id: zenodo_deposition
        env:
          ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
          ZENODO_API_URL: "https://sandbox.zenodo.org/api/deposit/depositions"
        run: |
          if [ -z "$ZENODO_ACCESS_TOKEN" ]; then
            echo "Error: ZENODO_ACCESS_TOKEN is not set."
            exit 1
          fi
      
          # Fetch existing depositions (check if there's an existing Concept)
          RESPONSE=$(curl -s -X GET "$ZENODO_API_URL" -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN")
      
          # Log the full response for debugging
          echo "Zenodo Response: $RESPONSE"
      
          # Check if the response contains any existing Concept (Concept ID)
          if echo "$RESPONSE" | jq 'type' | grep -q '"array"'; then
            # If the response is an array, check if there is an existing Concept
            if [ "$(echo "$RESPONSE" | jq length)" -eq 0 ]; then
              echo "No existing Concept found. Creating a new Concept..."
              RESPONSE=$(curl -s -X POST "$ZENODO_API_URL" \
                -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN" \
                -H "Content-Type: application/json" \
                --data '{}')
            fi
      
            # Parse the Concept ID (use existing or newly created one)
            CONCEPT_ID=$(echo "$RESPONSE" | jq -r '.[0].conceptrecid')
          else
            # If the response is an object, parse it accordingly
            CONCEPT_ID=$(echo "$RESPONSE" | jq -r '.conceptrecid')
          fi
      
          if [ -z "$CONCEPT_ID" ] || [ "$CONCEPT_ID" = "null" ]; then
            echo "Error: Failed to fetch or create Concept."
            exit 1
          fi
      
          # Print the Concept ID
          echo "Using Concept ID: $CONCEPT_ID"
      
          # Create a new Deposition with the existing or newly created Concept
          echo "Creating a new Deposition..."
          NEW_DEPOSITION=$(curl -s -X POST "$ZENODO_API_URL" \
            -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            --data '{"conceptrecid": "'"$CONCEPT_ID"'"}')
      
          # Parse the new Deposition ID
          NEW_DEPOSITION_ID=$(echo "$NEW_DEPOSITION" | jq -r '.id')
      
          if [ -z "$NEW_DEPOSITION_ID" ] || [ "$NEW_DEPOSITION_ID" = "null" ]; then
            echo "Error: Failed to create Deposition."
            exit 1
          fi
      
          # Print the new Deposition ID
          echo "New Deposition ID: $NEW_DEPOSITION_ID"
      
          # Set the environment variables for further steps
          echo "CONCEPT_ID=$CONCEPT_ID" >> $GITHUB_ENV
          echo "DEPOSITION_ID=$NEW_DEPOSITION_ID" >> $GITHUB_ENV
      
      - name: Upload ZIP to Zenodo
        env:
          ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
          ZENODO_API_URL: "https://sandbox.zenodo.org/api/deposit/depositions/$DEPOSITION_ID/files"
        run: |
          if [ ! -f "code.zip" ]; then
            echo "Error: code.zip not found!"
            exit 1
          fi

          # Upload the new version (ZIP file)
          RESPONSE=$(curl -s -X POST "$ZENODO_API_URL" \
            -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN" \
            -F "file=@code.zip;filename=code.zip")

          if [ "$(echo "$RESPONSE" | jq -r '.checksum')" = "null" ]; then
            echo "Error: Upload failed."
            exit 1
          fi

          echo "File uploaded successfully."

      - name: Publish Deposition as a New Version
        if: success()
        env:
          ZENODO_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
          ZENODO_API_URL: "https://sandbox.zenodo.org/api/deposit/depositions/$DEPOSITION_ID/actions/publish"
        run: |
          # Publish the new deposition (version)
          RESPONSE=$(curl -s -X POST "$ZENODO_API_URL" -H "Authorization: Bearer $ZENODO_ACCESS_TOKEN")

          if [ "$(echo "$RESPONSE" | jq -r '.submitted')" != "true" ]; then
            echo "Error: Publishing failed."
            exit 1
          fi

          echo "Deposition (new version) published successfully."